basePath: /api/v1
definitions:
  announcements.AnnouncementsPostRequest:
    properties:
      article:
        type: string
      cost:
        type: integer
      imageURL:
        type: string
      text:
        type: string
    type: object
  auth.AuthRequest:
    properties:
      password:
        example: "12345"
        type: string
      username:
        example: john_doe
        type: string
    type: object
  model.Announcement:
    properties:
      image_url:
        type: string
      is_owner:
        type: boolean
      owner_username:
        type: string
      price:
        type: integer
      text:
        type: string
      title:
        type: string
    type: object
  register.RegisterRequest:
    properties:
      password:
        example: "12345"
        type: string
      username:
        example: john_doe
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a backend service for VK test task.
  title: VK Test Backend API
  version: "1.0"
paths:
  /api/v1/announcements:
    get:
      description: Get a paginated list of announcements. This endpoint is public.
      parameters:
      - description: Page number for pagination (starts from 1)
        in: query
        name: page
        required: true
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Announcement'
            type: array
        "400":
          description: Invalid page or limit parameter
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - Bearer: []
      summary: Get announcements list
      tags:
      - Announcements
    post:
      consumes:
      - application/json
      description: Create an announcement for authorized users.
      parameters:
      - description: Announcement details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/announcements.AnnouncementsPostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Announcement successfully created
        "400":
          description: Invalid request payload
        "500":
          description: Internal server error
      security:
      - Bearer: []
      summary: Create an announcement
      tags:
      - Announcements
  /api/v1/auth:
    post:
      consumes:
      - application/json
      description: Auth user by username and password.
      parameters:
      - description: User authorization details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.AuthRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User successfully authorized
        "400":
          description: Invalid request payload or invalid username or invalid password
        "500":
          description: Internal server error
      summary: Auth user
      tags:
      - Users
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Registers a new user with a username and password.
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/register.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User successfully registered
        "400":
          description: Invalid request payload or user already exists
        "500":
          description: Internal server error
      summary: Register a new user
      tags:
      - Users
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
